[package]
name = "fll-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ev3dev-lang-rust = { version = "0.11.1", features = ["screen"] }
anyhow = { version = "1.0.57", features = ["backtrace"] }
# thiserror = "1.0.30"

# image = "0.23.14"
# imageproc = "0.22.0"

piet-common = { version = "0.5.0", package = "piet" }

toml = "0.5.9"
rusttype = "0.9.2"
num = "0.4.0"

[target.'cfg(not(target_arch = "armv5te"))'.dependencies]
minifb = "0.20.0"