[package]
name = "fll-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.57", features = ["backtrace"] }
# thiserror = "1.0.30"

image = { version = "0.24.2", default-features = false }
imageproc = { version = "0.23.0", default-features = false }

# piet = "0.5.0"
# piet-common = "0.5.0"

toml = "0.5.9"
rusttype = "0.9.2"
num = "0.4.0"

[dev-dependencies]
# plotters = "0.3.1"

[target.'cfg(target_arch = "arm")'.dependencies]
ev3dev-lang-rust = { version = "0.12.0", features = ["screen"] }

[target.'cfg(not(target_arch = "arm"))'.dependencies]
minifb = "0.20.0"